// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationsAPI.Data;

#nullable disable

namespace ReservationsAPI.Migrations
{
    [DbContext(typeof(ReservationsAPIContext))]
    [Migration("20260113182046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationsAPI.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("ReservationsAPI.Models.HallGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AZ")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("HallGroups");
                });

            modelBuilder.Entity("ReservationsAPI.Models.HallSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("HallGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<int>("ShowSeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallGroupId");

                    b.ToTable("HallSeats");
                });

            modelBuilder.Entity("ReservationsAPI.Models.HallGroup", b =>
                {
                    b.HasOne("ReservationsAPI.Models.Hall", "Hall")
                        .WithMany("HallGroups")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ReservationsAPI.Models.HallSeat", b =>
                {
                    b.HasOne("ReservationsAPI.Models.HallGroup", "HallGroup")
                        .WithMany("HallSeats")
                        .HasForeignKey("HallGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallGroup");
                });

            modelBuilder.Entity("ReservationsAPI.Models.Hall", b =>
                {
                    b.Navigation("HallGroups");
                });

            modelBuilder.Entity("ReservationsAPI.Models.HallGroup", b =>
                {
                    b.Navigation("HallSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
